export const foods = [
  {
    name: "white bread",
    calories: 265,
    grams: 100,
    protein: 9,
    carbs: 49,
    fats: 3.2,
  },
  {
    name: "whole wheat bread",
    calories: 247,
    grams: 100,
    protein: 13,
    carbs: 41,
    fats: 4.2,
  },
  {
    name: "bagel",
    calories: 250,
    grams: 100,
    protein: 10,
    carbs: 48,
    fats: 1.2,
  },
  {
    name: "croissant",
    calories: 406,
    grams: 100,
    protein: 8,
    carbs: 45,
    fats: 21,
  },
  {
    name: "tortilla",
    calories: 237,
    grams: 100,
    protein: 8.1,
    carbs: 49,
    fats: 2.8,
  },
  {
    name: "white rice",
    calories: 130,
    grams: 100,
    protein: 2.7,
    carbs: 28,
    fats: 0.3,
  },
  {
    name: "brown rice",
    calories: 123,
    grams: 100,
    protein: 2.7,
    carbs: 25.6,
    fats: 1,
  },
  {
    name: "spaghetti (cooked)",
    calories: 158,
    grams: 100,
    protein: 6,
    carbs: 31,
    fats: 0.9,
  },
  {
    name: "penne pasta (cooked)",
    calories: 157,
    grams: 100,
    protein: 5.8,
    carbs: 30.8,
    fats: 1.1,
  },
  {
    name: "mashed potatoes",
    calories: 88,
    grams: 100,
    protein: 1.7,
    carbs: 20,
    fats: 0.4,
  },
  {
    name: "baked potato",
    calories: 93,
    grams: 100,
    protein: 2.5,
    carbs: 21,
    fats: 0.1,
  },
  {
    name: "french fries",
    calories: 312,
    grams: 100,
    protein: 3.4,
    carbs: 41,
    fats: 15,
  },
  {
    name: "onion",
    calories: 40,
    grams: 100,
    protein: 1.1,
    carbs: 9.3,
    fats: 0.1,
  },
  {
    name: "cucumber",
    calories: 15,
    grams: 100,
    protein: 0.7,
    carbs: 3.6,
    fats: 0.1,
  },
  {
    name: "iceberg lettuce",
    calories: 14,
    grams: 100,
    protein: 0.9,
    carbs: 3,
    fats: 0.1,
  },
  {
    name: "coleslaw",
    calories: 152,
    grams: 100,
    protein: 1,
    carbs: 8,
    fats: 13,
  },
  {
    name: "cheddar cheese",
    calories: 403,
    grams: 100,
    protein: 25,
    carbs: 1.3,
    fats: 33,
  },
  {
    name: "mozzarella cheese",
    calories: 280,
    grams: 100,
    protein: 28,
    carbs: 2.2,
    fats: 17,
  },
  {
    name: "cottage cheese",
    calories: 98,
    grams: 100,
    protein: 11,
    carbs: 3.4,
    fats: 4.3,
  },
  {
    name: "greek yogurt",
    calories: 59,
    grams: 100,
    protein: 10,
    carbs: 3.6,
    fats: 0.4,
  },
  {
    name: "whole milk",
    calories: 61,
    grams: 100,
    protein: 3.2,
    carbs: 4.8,
    fats: 3.3,
  },
  {
    name: "skim milk",
    calories: 34,
    grams: 100,
    protein: 3.4,
    carbs: 5,
    fats: 0.1,
  },
  {
    name: "orange juice",
    calories: 45,
    grams: 100,
    protein: 0.7,
    carbs: 10.4,
    fats: 0.2,
  },
  {
    name: "apple juice",
    calories: 46,
    grams: 100,
    protein: 0.1,
    carbs: 11.3,
    fats: 0.1,
  },
  {
    name: "coffee (black)",
    calories: 1,
    grams: 100,
    protein: 0,
    carbs: 0,
    fats: 0,
  },
  {
    name: "mayonnaise",
    calories: 680,
    grams: 100,
    protein: 0.9,
    carbs: 0.6,
    fats: 75,
  },
  {
    name: "ketchup",
    calories: 112,
    grams: 100,
    protein: 1.3,
    carbs: 26,
    fats: 0.1,
  },
  {
    name: "barbecue sauce",
    calories: 150,
    grams: 100,
    protein: 1,
    carbs: 35,
    fats: 0.5,
  },
  {
    name: "soy sauce",
    calories: 53,
    grams: 100,
    protein: 8,
    carbs: 5.6,
    fats: 0.6,
  },
  {
    name: "granola",
    calories: 489,
    grams: 100,
    protein: 13,
    carbs: 64,
    fats: 20,
  },
  {
    name: "corn flakes",
    calories: 357,
    grams: 100,
    protein: 8,
    carbs: 84,
    fats: 0.4,
  },
  {
    name: "oatmeal (cooked)",
    calories: 68,
    grams: 100,
    protein: 2.4,
    carbs: 12,
    fats: 1.4,
  },
];
